'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class ValidationMessage
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Hepsa.Core.ValidationMessage", GetType(ValidationMessage).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to رفتار حساب {0} معمولا بستانکار می باشد.
        '''</summary>
        Public Shared ReadOnly Property AccountCreditBehaviourIsNotCorrect() As String
            Get
                Return ResourceManager.GetString("AccountCreditBehaviourIsNotCorrect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to حساب {0} معمولا بستانکار می باشد.
        '''</summary>
        Public Shared ReadOnly Property AccountCreditRemainderBehaviour() As String
            Get
                Return ResourceManager.GetString("AccountCreditRemainderBehaviour", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to رفتار حساب {0} معمولا بدهکار می باشد.
        '''</summary>
        Public Shared ReadOnly Property AccountDeptBehaviourIsNotCorrect() As String
            Get
                Return ResourceManager.GetString("AccountDeptBehaviourIsNotCorrect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to حساب {0} معمولا بدهکار می باشد.
        '''</summary>
        Public Shared ReadOnly Property AccountDeptRemainderBehaviour() As String
            Get
                Return ResourceManager.GetString("AccountDeptRemainderBehaviour", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to حساب {0} ، دارای زیرحساب می باشد.
        '''</summary>
        Public Shared ReadOnly Property AccountIsNotLastLevel() As String
            Get
                Return ResourceManager.GetString("AccountIsNotLastLevel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to چک به شماره {0} قبلا پرداخت شده است.
        '''</summary>
        Public Shared ReadOnly Property ChequeIsAlreadyPayed() As String
            Get
                Return ResourceManager.GetString("ChequeIsAlreadyPayed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to چک به شماره {0} در سیستم موجود می باشد.
        '''</summary>
        Public Shared ReadOnly Property ChequeIsExistsInSystem() As String
            Get
                Return ResourceManager.GetString("ChequeIsExistsInSystem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to چک {0} در وضعیت {1} می باشد.
        '''</summary>
        Public Shared ReadOnly Property ChequeIsInState() As String
            Get
                Return ResourceManager.GetString("ChequeIsInState", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to چک {0} سفید و در سیستم موجود می باشد.
        '''</summary>
        Public Shared ReadOnly Property ChequeIsMyChequeAndExistInSystem() As String
            Get
                Return ResourceManager.GetString("ChequeIsMyChequeAndExistInSystem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to چک به شماره {0} در سیستم موجود نمی باشد.
        '''</summary>
        Public Shared ReadOnly Property ChequeIsNotExist() As String
            Get
                Return ResourceManager.GetString("ChequeIsNotExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to چک به شماره {0} جزء اسناد پرداختنی می باشد.
        '''</summary>
        Public Shared ReadOnly Property ChequeIsPaymentDocument() As String
            Get
                Return ResourceManager.GetString("ChequeIsPaymentDocument", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to شماره چک تکراری می باشد.
        '''</summary>
        Public Shared ReadOnly Property ChequeIsRepeatitive() As String
            Get
                Return ResourceManager.GetString("ChequeIsRepeatitive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to مقدار {0} نمی تواند خالی باشد.
        '''</summary>
        Public Shared ReadOnly Property ChildAccountCanNotBeNULL() As String
            Get
                Return ResourceManager.GetString("ChildAccountCanNotBeNULL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سقف بستانکاری نباید بزرگتر از {0} باشد.
        '''</summary>
        Public Shared ReadOnly Property CreditorIsGratherThanParent() As String
            Get
                Return ResourceManager.GetString("CreditorIsGratherThanParent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سقف بستانکاری نباید کوچکتر از {0} باشد.
        '''</summary>
        Public Shared ReadOnly Property CreditorIsLessThanChild() As String
            Get
                Return ResourceManager.GetString("CreditorIsLessThanChild", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سقف بستانکاری حساب {0}  ،{1} {2} سرریز شده است.
        '''</summary>
        Public Shared ReadOnly Property CreditOverflow() As String
            Get
                Return ResourceManager.GetString("CreditOverflow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}، خالی است.
        '''</summary>
        Public Shared ReadOnly Property DataIsEmpty() As String
            Get
                Return ResourceManager.GetString("DataIsEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}، باید خالی باشد.
        '''</summary>
        Public Shared ReadOnly Property DataIsNotEmpty() As String
            Get
                Return ResourceManager.GetString("DataIsNotEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}، نامعتبر می باشد.
        '''</summary>
        Public Shared ReadOnly Property DataNotValid() As String
            Get
                Return ResourceManager.GetString("DataNotValid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to تاریخ شروع نباید مابین تاریخ شروع و پایان باشد.
        '''</summary>
        Public Shared ReadOnly Property DateRangeErrorEntered() As String
            Get
                Return ResourceManager.GetString("DateRangeErrorEntered", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سقف بدهکاری نباید بزرگتر از {0} باشد.
        '''</summary>
        Public Shared ReadOnly Property DeptorIsGratherThanParent() As String
            Get
                Return ResourceManager.GetString("DeptorIsGratherThanParent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سقف بدهکاری نباید کوچکتر از {0} باشد.
        '''</summary>
        Public Shared ReadOnly Property DeptorIsLessThanChild() As String
            Get
                Return ResourceManager.GetString("DeptorIsLessThanChild", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سقف بدهکاری حساب {0}  ،{1} {2} سرریز شده است.
        '''</summary>
        Public Shared ReadOnly Property DeptOverflow() As String
            Get
                Return ResourceManager.GetString("DeptOverflow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to جمع سند از اعتبار طرف حساب بیشتر است.
        '''</summary>
        Public Shared ReadOnly Property DocumentPriceGreaterThanActorCredit() As String
            Get
                Return ResourceManager.GetString("DocumentPriceGreaterThanActorCredit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سال مالی فوق باید سال مالی فعال باشد.
        '''</summary>
        Public Shared ReadOnly Property FiscalYearShouldBeDefault() As String
            Get
                Return ResourceManager.GetString("FiscalYearShouldBeDefault", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to از کالای {0} به تعداد {1} واحد موجود می باشد.
        '''</summary>
        Public Shared ReadOnly Property GoodExistance() As String
            Get
                Return ResourceManager.GetString("GoodExistance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to موجودی کالای {0}، از حداکثر موجودی بیشتر است.
        '''</summary>
        Public Shared ReadOnly Property GoodExistanceGreaterThanMaximumRequirement() As String
            Get
                Return ResourceManager.GetString("GoodExistanceGreaterThanMaximumRequirement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to موجودی کالای {0}، از حداقل موجودی کمتر است.
        '''</summary>
        Public Shared ReadOnly Property GoodExistanceLessThanMinimumRequirement() As String
            Get
                Return ResourceManager.GetString("GoodExistanceLessThanMinimumRequirement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to از کالای {0} به تعداد {1} واحد نزد مشتری موجود می باشد.
        '''</summary>
        Public Shared ReadOnly Property GoodIsNotInActor() As String
            Get
                Return ResourceManager.GetString("GoodIsNotInActor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سریال {0} از قبل موجود می باشد.
        '''</summary>
        Public Shared ReadOnly Property GoodSerialAlreadyExist() As String
            Get
                Return ResourceManager.GetString("GoodSerialAlreadyExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to از سریال مورد نظر {0} واحد موجود می باشد.
        '''</summary>
        Public Shared ReadOnly Property GoodSerialExistance() As String
            Get
                Return ResourceManager.GetString("GoodSerialExistance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to تعداد فیلدها نامعتبر است.
        '''</summary>
        Public Shared ReadOnly Property IncorectFieldCount() As String
            Get
                Return ResourceManager.GetString("IncorectFieldCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نوع داده {0} اشتباه است.
        '''</summary>
        Public Shared ReadOnly Property IncorrectDataType() As String
            Get
                Return ResourceManager.GetString("IncorrectDataType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} برابر {1} نمی باشد.
        '''</summary>
        Public Shared ReadOnly Property LogicOperationEqualError() As String
            Get
                Return ResourceManager.GetString("LogicOperationEqualError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} بزرگتر یا مساوی {1} نمی باشد.
        '''</summary>
        Public Shared ReadOnly Property LogicOperationGratherOrEqualError() As String
            Get
                Return ResourceManager.GetString("LogicOperationGratherOrEqualError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} بزرگتر از {1} نمی باشد.
        '''</summary>
        Public Shared ReadOnly Property LogicOperationGratherThanError() As String
            Get
                Return ResourceManager.GetString("LogicOperationGratherThanError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} کوچکتر یا مساوی {1} نمی باشد.
        '''</summary>
        Public Shared ReadOnly Property LogicOperationLessOrEqualError() As String
            Get
                Return ResourceManager.GetString("LogicOperationLessOrEqualError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} کوچکتر از {1} نمی باشد.
        '''</summary>
        Public Shared ReadOnly Property LogicOperationLessThanError() As String
            Get
                Return ResourceManager.GetString("LogicOperationLessThanError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} مخالف از {1} نمی باشد.
        '''</summary>
        Public Shared ReadOnly Property LogicOperationNotEqualError() As String
            Get
                Return ResourceManager.GetString("LogicOperationNotEqualError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to مقدار {0} باید خالی باشد.
        '''</summary>
        Public Shared ReadOnly Property ParentAccountShouldBeNULL() As String
            Get
                Return ResourceManager.GetString("ParentAccountShouldBeNULL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} ، موجود نمی باشد.
        '''</summary>
        Public Shared ReadOnly Property RelationError() As String
            Get
                Return ResourceManager.GetString("RelationError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to از سریال {0} به تعداد {1} واحد نزد مشتری موجود می باشد.
        '''</summary>
        Public Shared ReadOnly Property SerialIsNotInActor() As String
            Get
                Return ResourceManager.GetString("SerialIsNotInActor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to جمع تسویه اسناد بیشتر از جمع مبلغ آرتیکل ها می باشد.
        '''</summary>
        Public Shared ReadOnly Property TransactionDocumentSumGreaterThanArticleSum() As String
            Get
                Return ResourceManager.GetString("TransactionDocumentSumGreaterThanArticleSum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نامشخص.
        '''</summary>
        Public Shared ReadOnly Property Unkown() As String
            Get
                Return ResourceManager.GetString("Unkown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}، از قبل موجود می باشد.
        '''</summary>
        Public Shared ReadOnly Property ValueAlreadyExists() As String
            Get
                Return ResourceManager.GetString("ValueAlreadyExists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to مبلغ وارد شده   {0}    كمتر از نرخ عرف ‍‌‍‌  {1}   است.
        '''</summary>
        Public Shared ReadOnly Property ValueIsNotEquelWithPriceNorm() As String
            Get
                Return ResourceManager.GetString("ValueIsNotEquelWithPriceNorm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}، نباید بیشتر از {1} کاراکتر باشد.
        '''</summary>
        Public Shared ReadOnly Property ValueMaxLen() As String
            Get
                Return ResourceManager.GetString("ValueMaxLen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}، نباید کمتر از {1} کاراکتر باشد.
        '''</summary>
        Public Shared ReadOnly Property ValueMinLen() As String
            Get
                Return ResourceManager.GetString("ValueMinLen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}، نباید بزرگتر از &lt;{1}&gt; باشد.
        '''</summary>
        Public Shared ReadOnly Property ValueShouldNotGreater() As String
            Get
                Return ResourceManager.GetString("ValueShouldNotGreater", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}، نباید کوچکتر از &lt;{1}&gt; باشد.
        '''</summary>
        Public Shared ReadOnly Property ValueShouldNotLess() As String
            Get
                Return ResourceManager.GetString("ValueShouldNotLess", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
