'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Captions
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Hepsa.Core.Captions", GetType(Captions).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to مقایسه حسابهای {0} و {1}.
        '''</summary>
        Public Shared ReadOnly Property AccountComparision() As String
            Get
                Return ResourceManager.GetString("AccountComparision", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to دفتر {0}.
        '''</summary>
        Public Shared ReadOnly Property AccountDocumentReportName() As String
            Get
                Return ResourceManager.GetString("AccountDocumentReportName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to افزودن زیر شاخه.
        '''</summary>
        Public Shared ReadOnly Property AddChildCategory() As String
            Get
                Return ResourceManager.GetString("AddChildCategory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to افزودن شاخه.
        '''</summary>
        Public Shared ReadOnly Property AddParentCategory() As String
            Get
                Return ResourceManager.GetString("AddParentCategory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to حساب مقابل.
        '''</summary>
        Public Shared ReadOnly Property AllAccount() As String
            Get
                Return ResourceManager.GetString("AllAccount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to کدینگ.
        '''</summary>
        Public Shared ReadOnly Property Coding() As String
            Get
                Return ResourceManager.GetString("Coding", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to فرمت کدینگ.
        '''</summary>
        Public Shared ReadOnly Property CodingFormat() As String
            Get
                Return ResourceManager.GetString("CodingFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to قطعی کردن سند.
        '''</summary>
        Public Shared ReadOnly Property Conclucive() As String
            Get
                Return ResourceManager.GetString("Conclucive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to اطلاعات تماس.
        '''</summary>
        Public Shared ReadOnly Property ConnectionInformation() As String
            Get
                Return ResourceManager.GetString("ConnectionInformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to دفتر مرکز هزینه.
        '''</summary>
        Public Shared ReadOnly Property CostCenterReportName() As String
            Get
                Return ResourceManager.GetString("CostCenterReportName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بس.
        '''</summary>
        Public Shared ReadOnly Property Creditor() As String
            Get
                Return ResourceManager.GetString("Creditor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to منبع داده.
        '''</summary>
        Public Shared ReadOnly Property DataSource() As String
            Get
                Return ResourceManager.GetString("DataSource", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to عنوان جزء منبع داده.
        '''</summary>
        Public Shared ReadOnly Property DataSourceDetailTitle() As String
            Get
                Return ResourceManager.GetString("DataSourceDetailTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to عنوان منبع داده.
        '''</summary>
        Public Shared ReadOnly Property DataSourceTitle() As String
            Get
                Return ResourceManager.GetString("DataSourceTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to کد نوع داده.
        '''</summary>
        Public Shared ReadOnly Property DataTypeCode() As String
            Get
                Return ResourceManager.GetString("DataTypeCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to عنوان نوع داده.
        '''</summary>
        Public Shared ReadOnly Property DataTypeTitle() As String
            Get
                Return ResourceManager.GetString("DataTypeTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to حذف.
        '''</summary>
        Public Shared ReadOnly Property DeleteCategory() As String
            Get
                Return ResourceManager.GetString("DeleteCategory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to حذف فایل.
        '''</summary>
        Public Shared ReadOnly Property DeleteExtraFieldFile() As String
            Get
                Return ResourceManager.GetString("DeleteExtraFieldFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ید.
        '''</summary>
        Public Shared ReadOnly Property Deptor() As String
            Get
                Return ResourceManager.GetString("Deptor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to توضیح.
        '''</summary>
        Public Shared ReadOnly Property Description() As String
            Get
                Return ResourceManager.GetString("Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to تبدیل به {0}.
        '''</summary>
        Public Shared ReadOnly Property DocumentTypeConvert() As String
            Get
                Return ResourceManager.GetString("DocumentTypeConvert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} شماره {1}.
        '''</summary>
        Public Shared ReadOnly Property DocumentWithType() As String
            Get
                Return ResourceManager.GetString("DocumentWithType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ویرایش.
        '''</summary>
        Public Shared ReadOnly Property EditCategory() As String
            Get
                Return ResourceManager.GetString("EditCategory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ختم به.
        '''</summary>
        Public Shared ReadOnly Property EndsWith() As String
            Get
                Return ResourceManager.GetString("EndsWith", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to برابر با.
        '''</summary>
        Public Shared ReadOnly Property Equal() As String
            Get
                Return ResourceManager.GetString("Equal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to شناسه جدول-فیلد اضافه.
        '''</summary>
        Public Shared ReadOnly Property ExtaFieldTableID() As String
            Get
                Return ResourceManager.GetString("ExtaFieldTableID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to عنوان خاصیت.
        '''</summary>
        Public Shared ReadOnly Property ExtraField() As String
            Get
                Return ResourceManager.GetString("ExtraField", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نوع خاصیت.
        '''</summary>
        Public Shared ReadOnly Property ExtraFieldDataType() As String
            Get
                Return ResourceManager.GetString("ExtraFieldDataType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to اطلاعات شناور.
        '''</summary>
        Public Shared ReadOnly Property ExtraFieldInformation() As String
            Get
                Return ResourceManager.GetString("ExtraFieldInformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to الگوی خاصیت.
        '''</summary>
        Public Shared ReadOnly Property ExtraFieldTemplate() As String
            Get
                Return ResourceManager.GetString("ExtraFieldTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to فیلد.
        '''</summary>
        Public Shared ReadOnly Property Field() As String
            Get
                Return ResourceManager.GetString("Field", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to الگوی فیلد.
        '''</summary>
        Public Shared ReadOnly Property FieldPattern() As String
            Get
                Return ResourceManager.GetString("FieldPattern", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to عنوان الگوی فیلد.
        '''</summary>
        Public Shared ReadOnly Property FieldTemplateTitle() As String
            Get
                Return ResourceManager.GetString("FieldTemplateTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to کل.
        '''</summary>
        Public Shared ReadOnly Property FirstLevelDefaultName() As String
            Get
                Return ResourceManager.GetString("FirstLevelDefaultName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to تولید شده از {0} شماره {1}.
        '''</summary>
        Public Shared ReadOnly Property GeneratedFromDocument() As String
            Get
                Return ResourceManager.GetString("GeneratedFromDocument", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بزرگتر يا مساوي.
        '''</summary>
        Public Shared ReadOnly Property GreaterOrEqual() As String
            Get
                Return ResourceManager.GetString("GreaterOrEqual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بزرگتر از.
        '''</summary>
        Public Shared ReadOnly Property GreaterThan() As String
            Get
                Return ResourceManager.GetString("GreaterThan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to گروه.
        '''</summary>
        Public Shared ReadOnly Property Group() As String
            Get
                Return ResourceManager.GetString("Group", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to جدول گروه.
        '''</summary>
        Public Shared ReadOnly Property GroupTable() As String
            Get
                Return ResourceManager.GetString("GroupTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to راهنما.
        '''</summary>
        Public Shared ReadOnly Property Help() As String
            Get
                Return ResourceManager.GetString("Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to شامل.
        '''</summary>
        Public Shared ReadOnly Property Includes() As String
            Get
                Return ResourceManager.GetString("Includes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to آیتم.
        '''</summary>
        Public Shared ReadOnly Property Item() As String
            Get
                Return ResourceManager.GetString("Item", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to دفتر حساب.
        '''</summary>
        Public Shared ReadOnly Property JournalReportName() As String
            Get
                Return ResourceManager.GetString("JournalReportName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to كوچكتر يا مساوي.
        '''</summary>
        Public Shared ReadOnly Property LessOrEqual() As String
            Get
                Return ResourceManager.GetString("LessOrEqual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to كوچكتر از.
        '''</summary>
        Public Shared ReadOnly Property LessThan() As String
            Get
                Return ResourceManager.GetString("LessThan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to افزودن زیر شاخه به {0}.
        '''</summary>
        Public Shared ReadOnly Property NewCodingValueCaption() As String
            Get
                Return ResourceManager.GetString("NewCodingValueCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نا برابر با.
        '''</summary>
        Public Shared ReadOnly Property NotEqual() As String
            Get
                Return ResourceManager.GetString("NotEqual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to غير شامل.
        '''</summary>
        Public Shared ReadOnly Property NotInclude() As String
            Get
                Return ResourceManager.GetString("NotInclude", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to والد.
        '''</summary>
        Public Shared ReadOnly Property Parent() As String
            Get
                Return ResourceManager.GetString("Parent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to پرداخت.
        '''</summary>
        Public Shared ReadOnly Property Payment() As String
            Get
                Return ResourceManager.GetString("Payment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بابت سند پرداخت به شماره {0}.
        '''</summary>
        Public Shared ReadOnly Property PaymentDescription() As String
            Get
                Return ResourceManager.GetString("PaymentDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to فروردین|اردیبهشت|خرداد|تیر|مرداد|شهریور|مهر|آبان|آذر|دی|بهمن|اسفند.
        '''</summary>
        Public Shared ReadOnly Property PersianMonth() As String
            Get
                Return ResourceManager.GetString("PersianMonth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ضریب تبدیل به {0}.
        '''</summary>
        Public Shared ReadOnly Property RationTo() As String
            Get
                Return ResourceManager.GetString("RationTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ضریب تبدیل به واحد اصلی.
        '''</summary>
        Public Shared ReadOnly Property RatioToMainCountUnit() As String
            Get
                Return ResourceManager.GetString("RatioToMainCountUnit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to دریافت.
        '''</summary>
        Public Shared ReadOnly Property Receipt() As String
            Get
                Return ResourceManager.GetString("Receipt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بابت سند دریافت به شماره {0}.
        '''</summary>
        Public Shared ReadOnly Property ReceiptDescription() As String
            Get
                Return ResourceManager.GetString("ReceiptDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to مانده.
        '''</summary>
        Public Shared ReadOnly Property Remainder() As String
            Get
                Return ResourceManager.GetString("Remainder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ثبت.
        '''</summary>
        Public Shared ReadOnly Property Save() As String
            Get
                Return ResourceManager.GetString("Save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ثبت و خروج.
        '''</summary>
        Public Shared ReadOnly Property SaveAndClose() As String
            Get
                Return ResourceManager.GetString("SaveAndClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ثبت و بعدی.
        '''</summary>
        Public Shared ReadOnly Property SaveAndContinue() As String
            Get
                Return ResourceManager.GetString("SaveAndContinue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to بازیابی فایل.
        '''</summary>
        Public Shared ReadOnly Property SaveExtraFieldFile() As String
            Get
                Return ResourceManager.GetString("SaveExtraFieldFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to جستجو.
        '''</summary>
        Public Shared ReadOnly Property Search() As String
            Get
                Return ResourceManager.GetString("Search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to شروع با.
        '''</summary>
        Public Shared ReadOnly Property StartsWith() As String
            Get
                Return ResourceManager.GetString("StartsWith", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to جمع بستانکار.
        '''</summary>
        Public Shared ReadOnly Property SumCredit() As String
            Get
                Return ResourceManager.GetString("SumCredit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to جمع بدهکار.
        '''</summary>
        Public Shared ReadOnly Property SumDept() As String
            Get
                Return ResourceManager.GetString("SumDept", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to جدول.
        '''</summary>
        Public Shared ReadOnly Property Table() As String
            Get
                Return ResourceManager.GetString("Table", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to گره.
        '''</summary>
        Public Shared ReadOnly Property Tie() As String
            Get
                Return ResourceManager.GetString("Tie", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نام گره.
        '''</summary>
        Public Shared ReadOnly Property TieName() As String
            Get
                Return ResourceManager.GetString("TieName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to عنوان.
        '''</summary>
        Public Shared ReadOnly Property Title() As String
            Get
                Return ResourceManager.GetString("Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to تراز آزمایشی زیرحساب های حساب منتخب.
        '''</summary>
        Public Shared ReadOnly Property TrialBalanceAccountCaption() As String
            Get
                Return ResourceManager.GetString("TrialBalanceAccountCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to تراز آزمایشی در سطح {0}.
        '''</summary>
        Public Shared ReadOnly Property TrialBalanceAccountLevelCaption() As String
            Get
                Return ResourceManager.GetString("TrialBalanceAccountLevelCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to غیر قطعی کردن سند.
        '''</summary>
        Public Shared ReadOnly Property UnConclucive() As String
            Get
                Return ResourceManager.GetString("UnConclucive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to انتخاب فایل.
        '''</summary>
        Public Shared ReadOnly Property UploadExtraFieldFile() As String
            Get
                Return ResourceManager.GetString("UploadExtraFieldFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to کاربر.
        '''</summary>
        Public Shared ReadOnly Property User() As String
            Get
                Return ResourceManager.GetString("User", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to مقدار.
        '''</summary>
        Public Shared ReadOnly Property Value() As String
            Get
                Return ResourceManager.GetString("Value", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
