'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Exceptions
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Hepsa.Core.Exceptions", GetType(Exceptions).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to کپی حساب ها با موفقیت انجام شد.
        '''</summary>
        Public Shared ReadOnly Property AccountCopyCompletedSuccessfuly() As String
            Get
                Return ResourceManager.GetString("AccountCopyCompletedSuccessfuly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to حساب (های) زیر دارای سند می باشند و قابل حذف نمی باشند .
        '''</summary>
        Public Shared ReadOnly Property AccountFormalAccount_Account_CannotDelete() As String
            Get
                Return ResourceManager.GetString("AccountFormalAccount_Account_CannotDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to تفصیلی (های)  شناور زیر دارای سند می باشند و قابل حذف نمی باشند.
        '''</summary>
        Public Shared ReadOnly Property AccountFormalAccount_FormalAccount_Cannot() As String
            Get
                Return ResourceManager.GetString("AccountFormalAccount_FormalAccount_Cannot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to کد حساب سرریز شده است.
        '''</summary>
        Public Shared ReadOnly Property AccountID_nvcOverFlow() As String
            Get
                Return ResourceManager.GetString("AccountID_nvcOverFlow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to شماره حساب خالی است.
        '''</summary>
        Public Shared ReadOnly Property AccountIDIsEmpty() As String
            Get
                Return ResourceManager.GetString("AccountIDIsEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to حساب {0} در گردش است.
        '''</summary>
        Public Shared ReadOnly Property AccountIsInUse() As String
            Get
                Return ResourceManager.GetString("AccountIsInUse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سرفصل حساب مشخص شده آخرین سطح حساب می باشد و نمی تواند دارای زیر حساب گردد.
        '''</summary>
        Public Shared ReadOnly Property AccountIsLastLevelAccount() As String
            Get
                Return ResourceManager.GetString("AccountIsLastLevelAccount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to حساب دارای زیر حساب می باشد.
        '''</summary>
        Public Shared ReadOnly Property AccountIsNotLastLevel() As String
            Get
                Return ResourceManager.GetString("AccountIsNotLastLevel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سطح حساب خالی است.
        '''</summary>
        Public Shared ReadOnly Property AccountLevelIsEmpty() As String
            Get
                Return ResourceManager.GetString("AccountLevelIsEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to کد حساب از فرمت سرفصل حساب ها سرریز می کند.
        '''</summary>
        Public Shared ReadOnly Property AccountLevelIsOverFlow() As String
            Get
                Return ResourceManager.GetString("AccountLevelIsOverFlow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to حساب {0} یافت نشد.
        '''</summary>
        Public Shared ReadOnly Property AccountNotFound() As String
            Get
                Return ResourceManager.GetString("AccountNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to حساب {0} فضای کافی برای کپی حساب ها ندارد.
        '''</summary>
        Public Shared ReadOnly Property AccountsHaveNotEnoughSpace() As String
            Get
                Return ResourceManager.GetString("AccountsHaveNotEnoughSpace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to طرف حساب مورد نظر موجود نمی باشد.
        '''</summary>
        Public Shared ReadOnly Property ActorIsNotExists() As String
            Get
                Return ResourceManager.GetString("ActorIsNotExists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to طرف حسابی انتخاب نشده است.
        '''</summary>
        Public Shared ReadOnly Property ActorNotSelected() As String
            Get
                Return ResourceManager.GetString("ActorNotSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to آیا از حذف کلیه آرتیکل ها اطمینان دارید؟.
        '''</summary>
        Public Shared ReadOnly Property AllArticleDeleteConfirm() As String
            Get
                Return ResourceManager.GetString("AllArticleDeleteConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to آیا از حذف کلیه کالاها اطمینان دارید؟.
        '''</summary>
        Public Shared ReadOnly Property AllGoodDeleteConfirm() As String
            Get
                Return ResourceManager.GetString("AllGoodDeleteConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to آیا از حذف کلیه سریالها اطمینان دارید؟.
        '''</summary>
        Public Shared ReadOnly Property AllSerialDeleteConfirm() As String
            Get
                Return ResourceManager.GetString("AllSerialDeleteConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to آیا مایل به خروج از برنامه هستید؟.
        '''</summary>
        Public Shared ReadOnly Property AreTouSureToExitProgram() As String
            Get
                Return ResourceManager.GetString("AreTouSureToExitProgram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to آیا برای قطعی کردن اسناد اطمینان دارید؟.
        '''</summary>
        Public Shared ReadOnly Property AreYouSoureForConclusive() As String
            Get
                Return ResourceManager.GetString("AreYouSoureForConclusive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to آیا مایل به بستن فرم می باشید؟.
        '''</summary>
        Public Shared ReadOnly Property AreYouSureToCloseForm() As String
            Get
                Return ResourceManager.GetString("AreYouSureToCloseForm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to آرتیکل جاری فاقد حساب است.
        '''</summary>
        Public Shared ReadOnly Property ArticleNotHaveAccount() As String
            Get
                Return ResourceManager.GetString("ArticleNotHaveAccount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to آرتیکل شماره {0} معتبر نمی باشد.
        '''</summary>
        Public Shared ReadOnly Property ArticleNotValid() As String
            Get
                Return ResourceManager.GetString("ArticleNotValid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to امکان انتقال به سال مالی حاوی اطلاعات وجود ندارد.
        '''</summary>
        Public Shared ReadOnly Property CannotTransferToFullFiscalYear() As String
            Get
                Return ResourceManager.GetString("CannotTransferToFullFiscalYear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to گروه در جریان می باشد.
        '''</summary>
        Public Shared ReadOnly Property CategoryIsInUse() As String
            Get
                Return ResourceManager.GetString("CategoryIsInUse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to چک شماره {0} قبلا پرداخت شده است.
        '''</summary>
        Public Shared ReadOnly Property ChequeHasAllreadyDelivered() As String
            Get
                Return ResourceManager.GetString("ChequeHasAllreadyDelivered", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to چک شماره {0} قبلا دریافت شده است.
        '''</summary>
        Public Shared ReadOnly Property ChequeHasAllreadyReceived() As String
            Get
                Return ResourceManager.GetString("ChequeHasAllreadyReceived", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Public Shared ReadOnly Property ChequeInReceiptionDescription() As String
            Get
                Return ResourceManager.GetString("ChequeInReceiptionDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to وضعیت چک تغییر کرده است.
        '''</summary>
        Public Shared ReadOnly Property ChequeStatusIsChanged() As String
            Get
                Return ResourceManager.GetString("ChequeStatusIsChanged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سال مالی مورد نظر حاوی اطلاعات می باشد. آیا می خواهید اطلاعات سال مالی پاک شود؟.
        '''</summary>
        Public Shared ReadOnly Property ClearFiscalYearDataPrompt() As String
            Get
                Return ResourceManager.GetString("ClearFiscalYearDataPrompt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to فرمت کدینگ یافت نشد.
        '''</summary>
        Public Shared ReadOnly Property CodingFormatNotExist() As String
            Get
                Return ResourceManager.GetString("CodingFormatNotExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to کدینگ در جریان می باشد.
        '''</summary>
        Public Shared ReadOnly Property CodingInUse() As String
            Get
                Return ResourceManager.GetString("CodingInUse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to عملیات با موفقیت انجام شد.
        '''</summary>
        Public Shared ReadOnly Property CompletSuccessful() As String
            Get
                Return ResourceManager.GetString("CompletSuccessful", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to آیا مایل به حذف می باشید؟.
        '''</summary>
        Public Shared ReadOnly Property DeleteConfirm() As String
            Get
                Return ResourceManager.GetString("DeleteConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to کد حساب مقصد خالی است.
        '''</summary>
        Public Shared ReadOnly Property DestinationAccountID_nvcIsEmpty() As String
            Get
                Return ResourceManager.GetString("DestinationAccountID_nvcIsEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ردیف های مشخص شده ، معتبر نمی باشد.
        '''</summary>
        Public Shared ReadOnly Property DocumentArticleNotValid() As String
            Get
                Return ResourceManager.GetString("DocumentArticleNotValid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to امکان حذف سند بعد از تایید وجود ندارد.
        '''</summary>
        Public Shared ReadOnly Property DocumentConfirmedDeletePermision() As String
            Get
                Return ResourceManager.GetString("DocumentConfirmedDeletePermision", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to امکان ویرایش سند بعد از تایید وجود ندارد.
        '''</summary>
        Public Shared ReadOnly Property DocumentConfirmedEditPermision() As String
            Get
                Return ResourceManager.GetString("DocumentConfirmedEditPermision", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to قیمت آرتیکل های سند وارد نشده است.
        '''</summary>
        Public Shared ReadOnly Property DocumentHasNoPrice() As String
            Get
                Return ResourceManager.GetString("DocumentHasNoPrice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سند فوق تایید گردیده است و قابل حذف نمی باشد.
        '''</summary>
        Public Shared ReadOnly Property DocumentIsConfirmedAndCanNotBeDelete() As String
            Get
                Return ResourceManager.GetString("DocumentIsConfirmedAndCanNotBeDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سند فوق تایید گردیده است و قابل ویرایش نمی باشد.
        '''</summary>
        Public Shared ReadOnly Property DocumentIsConfirmedAndCanNotBeEdit() As String
            Get
                Return ResourceManager.GetString("DocumentIsConfirmedAndCanNotBeEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نوع سند اشتباه است.
        '''</summary>
        Public Shared ReadOnly Property DocumentTypeIsIncorrect() As String
            Get
                Return ResourceManager.GetString("DocumentTypeIsIncorrect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to عنوان {0} از قبل موجود می باشد.
        '''</summary>
        Public Shared ReadOnly Property DuplicateName() As String
            Get
                Return ResourceManager.GetString("DuplicateName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to آیا برای ویرایش دریافت به شماره {0} مطمئن هستید؟.
        '''</summary>
        Public Shared ReadOnly Property EditReceiptConfirm() As String
            Get
                Return ResourceManager.GetString("EditReceiptConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to آیا برای ویرایش سند حسابداری به شماره {0} مطمئن هستید؟.
        '''</summary>
        Public Shared ReadOnly Property EditVoucherConfirm() As String
            Get
                Return ResourceManager.GetString("EditVoucherConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to انتقال به اکسل با خطا متوقف شد. لطفا بعد از حصول اطمینان از نصب آفیس 2007 دوباره تلاش کنید.
        '''</summary>
        Public Shared ReadOnly Property ExcelExportError() As String
            Get
                Return ResourceManager.GetString("ExcelExportError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to انتقال به اکسل به اتمام رسید.
        '''</summary>
        Public Shared ReadOnly Property ExportToExcelComplete() As String
            Get
                Return ResourceManager.GetString("ExportToExcelComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to تفصیلی شناور {0} با حساب {1} سازگار نمی باشد.
        '''</summary>
        Public Shared ReadOnly Property FormalAccountIsNotCompatableWithAccount() As String
            Get
                Return ResourceManager.GetString("FormalAccountIsNotCompatableWithAccount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to کالا مشخص نشده است.
        '''</summary>
        Public Shared ReadOnly Property GoodIsNotDefine() As String
            Get
                Return ResourceManager.GetString("GoodIsNotDefine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to کالای مورد نظر موجود نمی باشد.
        '''</summary>
        Public Shared ReadOnly Property GoodIsNotExists() As String
            Get
                Return ResourceManager.GetString("GoodIsNotExists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to کالای {0} سریالی نمی باشد.
        '''</summary>
        Public Shared ReadOnly Property GoodIsNotSerialable() As String
            Get
                Return ResourceManager.GetString("GoodIsNotSerialable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to موجودی کالای {0} از {1} {2} کمتر است.
        '''</summary>
        Public Shared ReadOnly Property GoodNotEnough() As String
            Get
                Return ResourceManager.GetString("GoodNotEnough", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to در انبار {0} به تعداد {1} از کالای {2} موجود است..
        '''</summary>
        Public Shared ReadOnly Property GoodNotExistsInWareHouse() As String
            Get
                Return ResourceManager.GetString("GoodNotExistsInWareHouse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} با {1} در ارتباط است.
        '''</summary>
        Public Shared ReadOnly Property HaveRelation() As String
            Get
                Return ResourceManager.GetString("HaveRelation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to نرم افزار مالی همراهان سیستم فاقد شرکت می باشد، آیا مایل به ایجاد شرکت هستید؟.
        '''</summary>
        Public Shared ReadOnly Property InsertNewCompany() As String
            Get
                Return ResourceManager.GetString("InsertNewCompany", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to شرکت {0} فاقد سال مالی می باشد، آیا مایل به ایجاد سال مالی هستید؟.
        '''</summary>
        Public Shared ReadOnly Property InsertNewFiscalYear() As String
            Get
                Return ResourceManager.GetString("InsertNewFiscalYear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ترتیب سریال (ها) بر حسب نوع خروجی نا معتبر می باشد.
        '''</summary>
        Public Shared ReadOnly Property InvalidOutputTypeSerial() As String
            Get
                Return ResourceManager.GetString("InvalidOutputTypeSerial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to شناسه کاربری و/یا گذر واژه اشتباه می باشد.
        '''</summary>
        Public Shared ReadOnly Property InvalidUserNameOrPassword() As String
            Get
                Return ResourceManager.GetString("InvalidUserNameOrPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to خطایی یافت نشد.
        '''</summary>
        Public Shared ReadOnly Property NoErrorFound() As String
            Get
                Return ResourceManager.GetString("NoErrorFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to کد حساب مبدا خالی است.
        '''</summary>
        Public Shared ReadOnly Property OffspringAccountID_nvcIsEmpty() As String
            Get
                Return ResourceManager.GetString("OffspringAccountID_nvcIsEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سال مالی جاری ، فاقد ساختار سرفصل حساب می باشد
        '''لطفا ابتدا ساختار سرفصل حساب را وارد کنید.
        '''</summary>
        Public Shared ReadOnly Property PleaseAddFiscalYearAccountLevel() As String
            Get
                Return ResourceManager.GetString("PleaseAddFiscalYearAccountLevel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سال مالی جاری ، فاقد ساختار تفصیلی شناور می باشد
        '''لطفا ابتدا ساختار تفصیلی شناور را وارد کنید.
        '''</summary>
        Public Shared ReadOnly Property PleaseAddFiscalYearFormalAccountLevel() As String
            Get
                Return ResourceManager.GetString("PleaseAddFiscalYearFormalAccountLevel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to قبل از حذف آرتیکل ها نمی توانید طرف حساب را تغییر دهید.
        '''</summary>
        Public Shared ReadOnly Property ReceiptDeliverActorCannotChange() As String
            Get
                Return ResourceManager.GetString("ReceiptDeliverActorCannotChange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ردیف های مشخص شده ، معتبر نمی باشد.
        '''</summary>
        Public Shared ReadOnly Property ReceiptDeliverArticleNotValid() As String
            Get
                Return ResourceManager.GetString("ReceiptDeliverArticleNotValid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to امکان حذف سند بعد از تایید وجود ندارد.
        '''</summary>
        Public Shared ReadOnly Property ReceiptDeliverConfirmedDeletePermision() As String
            Get
                Return ResourceManager.GetString("ReceiptDeliverConfirmedDeletePermision", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to امکان ویرایش سند بعد از تایید وجود ندارد.
        '''</summary>
        Public Shared ReadOnly Property ReceiptDeliverConfirmedEditPermision() As String
            Get
                Return ResourceManager.GetString("ReceiptDeliverConfirmedEditPermision", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to قیمت آرتیکل های سند وارد نشده است.
        '''</summary>
        Public Shared ReadOnly Property ReceiptDeliverHasNoPrice() As String
            Get
                Return ResourceManager.GetString("ReceiptDeliverHasNoPrice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to شماره سند خالی است.
        '''</summary>
        Public Shared ReadOnly Property ReceiptNoIsEmpty() As String
            Get
                Return ResourceManager.GetString("ReceiptNoIsEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} مورد نظر از قبل موجود می باشد.
        '''</summary>
        Public Shared ReadOnly Property RecordAlreadyExist() As String
            Get
                Return ResourceManager.GetString("RecordAlreadyExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} مورد نظر یافت نشد.
        '''</summary>
        Public Shared ReadOnly Property RecordNotFound() As String
            Get
                Return ResourceManager.GetString("RecordNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to موردی یافت نشد.
        '''</summary>
        Public Shared ReadOnly Property SearchNotFound() As String
            Get
                Return ResourceManager.GetString("SearchNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to موردی یافت نشد.
        '''</summary>
        Public Shared ReadOnly Property SearchResualtIsEmpty() As String
            Get
                Return ResourceManager.GetString("SearchResualtIsEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to حسابی را انتخاب کنید.
        '''</summary>
        Public Shared ReadOnly Property SelectAnAccount() As String
            Get
                Return ResourceManager.GetString("SelectAnAccount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to آرتیکلی انتخاب نشده است.
        '''</summary>
        Public Shared ReadOnly Property SelectArticle() As String
            Get
                Return ResourceManager.GetString("SelectArticle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to چکی را انتخاب کنید.
        '''</summary>
        Public Shared ReadOnly Property SelectCheque() As String
            Get
                Return ResourceManager.GetString("SelectCheque", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to کالایی انتخاب نشده است.
        '''</summary>
        Public Shared ReadOnly Property SelectGood() As String
            Get
                Return ResourceManager.GetString("SelectGood", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سریالی انتخاب نشده است.
        '''</summary>
        Public Shared ReadOnly Property SelectSerial() As String
            Get
                Return ResourceManager.GetString("SelectSerial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to حساب معتبر انتخاب نشده است.
        '''</summary>
        Public Shared ReadOnly Property SelectValidAccount() As String
            Get
                Return ResourceManager.GetString("SelectValidAccount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to تعداد سریال برابر تعداد کالا نمی باشد.
        '''</summary>
        Public Shared ReadOnly Property SerialCountIsNotEquleGoodCount() As String
            Get
                Return ResourceManager.GetString("SerialCountIsNotEquleGoodCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to شماره سریال های وارد شده مربوط به کالای {0} با تعداد آن همخوانی ندارد.
        '''</summary>
        Public Shared ReadOnly Property SerialCountNotMatchWithGoodCount() As String
            Get
                Return ResourceManager.GetString("SerialCountNotMatchWithGoodCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سریال با تاریخ تولید و اعتبار متفاوت از قبل موجود می باشد.
        '''</summary>
        Public Shared ReadOnly Property SerialIsAlreadyExistWithoutEqualDate() As String
            Get
                Return ResourceManager.GetString("SerialIsAlreadyExistWithoutEqualDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سریال {0}، تکراری است.
        '''</summary>
        Public Shared ReadOnly Property SerialIsRepretive() As String
            Get
                Return ResourceManager.GetString("SerialIsRepretive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سریال(های) زیر موجود نمی باشد:
        '''{0}.
        '''</summary>
        Public Shared ReadOnly Property SerialNotFound() As String
            Get
                Return ResourceManager.GetString("SerialNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سریال(های) زیر در طرف حساب {0} موجود نمی باشد:
        '''{1}.
        '''</summary>
        Public Shared ReadOnly Property SerialsIsNotInActor() As String
            Get
                Return ResourceManager.GetString("SerialsIsNotInActor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سریال(های) زیر در سند {0} موجود نمی باشد:
        '''{1}.
        '''</summary>
        Public Shared ReadOnly Property SerialsIsNotInDocument() As String
            Get
                Return ResourceManager.GetString("SerialsIsNotInDocument", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to در هنگام برپایی اتصال به بانک اطلاعاتی خطایی رخ داده است
        '''این مشکل ممکن است به دلیل تنظیمات پایگاه داده مبنی بر عدم پذیرش اتصال از راه دور توسط پایگاه داده باشد.
        '''</summary>
        Public Shared ReadOnly Property SQL53() As String
            Get
                Return ResourceManager.GetString("SQL53", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to رکورد مورد نظر با &quot;{0}&quot; در ارتباط می باشد.
        '''</summary>
        Public Shared ReadOnly Property SQL547() As String
            Get
                Return ResourceManager.GetString("SQL547", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to آرتیکلی موجود نمی باشد.
        '''</summary>
        Public Shared ReadOnly Property ThereIsNoArticle() As String
            Get
                Return ResourceManager.GetString("ThereIsNoArticle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to کالایی موجود نمی باشد.
        '''</summary>
        Public Shared ReadOnly Property ThereIsNoGood() As String
            Get
                Return ResourceManager.GetString("ThereIsNoGood", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سریالی موجود نمی باشد.
        '''</summary>
        Public Shared ReadOnly Property ThereIsNoSerial() As String
            Get
                Return ResourceManager.GetString("ThereIsNoSerial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to گزارشی جهت چاپ ایجاد نگردیده است.
        '''</summary>
        Public Shared ReadOnly Property ThereIsNotReportForPrint() As String
            Get
                Return ResourceManager.GetString("ThereIsNotReportForPrint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to امکان حذف تراکنش مرتبط با سند وجود ندارد.
        '''</summary>
        Public Shared ReadOnly Property TransactionDeletePermision() As String
            Get
                Return ResourceManager.GetString("TransactionDeletePermision", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to امکان ویرایش تراکنش مرتبط با سند وجود ندارد.
        '''</summary>
        Public Shared ReadOnly Property TransactionEditPermision() As String
            Get
                Return ResourceManager.GetString("TransactionEditPermision", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to اعتبار کاربری شما در تاریخ {0} پایان یافته است.
        '''</summary>
        Public Shared ReadOnly Property UserExpireDateError() As String
            Get
                Return ResourceManager.GetString("UserExpireDateError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to کاربر گرامی ، اکانت شما غیر فعال می باشد.
        '''</summary>
        Public Shared ReadOnly Property UserIsNotActive() As String
            Get
                Return ResourceManager.GetString("UserIsNotActive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to کاربر گرامی ، شما از تاریخ {0} مجاز به استفاده از سیستم می باشید.
        '''</summary>
        Public Shared ReadOnly Property UserStartDateError() As String
            Get
                Return ResourceManager.GetString("UserStartDateError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ردیف های مشخص شده ، معتبر نمی باشد.
        '''</summary>
        Public Shared ReadOnly Property VoucherArticleNotValid() As String
            Get
                Return ResourceManager.GetString("VoucherArticleNotValid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سند حسابداری فوق تغییر یافته است آیا تغییرات شما اعمال شود؟.
        '''</summary>
        Public Shared ReadOnly Property VoucherChanged() As String
            Get
                Return ResourceManager.GetString("VoucherChanged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سند فوق تراز نمی باشد.
        '''</summary>
        Public Shared ReadOnly Property VoucherIsNotInRegistrationMode() As String
            Get
                Return ResourceManager.GetString("VoucherIsNotInRegistrationMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to شماره سند قبلا ثبت شده است.
        '''</summary>
        Public Shared ReadOnly Property VoucherNOAlreadyExist() As String
            Get
                Return ResourceManager.GetString("VoucherNOAlreadyExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to سندی را انتخاب کنید.
        '''</summary>
        Public Shared ReadOnly Property VoucherNotSelected() As String
            Get
                Return ResourceManager.GetString("VoucherNotSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to انبار مورد نظر موجود نمی باشد.
        '''</summary>
        Public Shared ReadOnly Property WareHouseIsNotNotExists() As String
            Get
                Return ResourceManager.GetString("WareHouseIsNotNotExists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to یک انبار گردانی انتخاب کنید.
        '''</summary>
        Public Shared ReadOnly Property WarehousingNotSelected() As String
            Get
                Return ResourceManager.GetString("WarehousingNotSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to تعداد را برای چاپ انتخاب کنید.
        '''</summary>
        Public Shared ReadOnly Property WarehousingPrintCountNotSelected() As String
            Get
                Return ResourceManager.GetString("WarehousingPrintCountNotSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to برای سند از نوع {0} نباید سریال وارد شود.
        '''</summary>
        Public Shared ReadOnly Property YouShouldNotEnterSerial() As String
            Get
                Return ResourceManager.GetString("YouShouldNotEnterSerial", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
