//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPS.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionCs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionCs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HPS.Exceptions.ExceptionCs", typeof(ExceptionCs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرویس کنترل تردد قطع می باشد.
        /// </summary>
        internal static string ANPRServiceOfflineAlarm {
            get {
                return ResourceManager.GetString("ANPRServiceOfflineAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارتباط با دوربین برقرار نیست.
        /// </summary>
        internal static string ANPRServiceOfflineDueToCameraAlarm {
            get {
                return ResourceManager.GetString("ANPRServiceOfflineDueToCameraAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  سنسورها قطع می باشد.
        /// </summary>
        internal static string ANPRServiceOfflineDueToSensorAlarm {
            get {
                return ResourceManager.GetString("ANPRServiceOfflineDueToSensorAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا مایل به خروج از برنامه هستید؟.
        /// </summary>
        internal static string AreuSureToExitProgram {
            get {
                return ResourceManager.GetString("AreuSureToExitProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا مایل به بستن فرم می باشید؟.
        /// </summary>
        internal static string AreYouSureToCloseForm {
            get {
                return ResourceManager.GetString("AreYouSureToCloseForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خوردوای انتخاب نشده است.
        /// </summary>
        internal static string CarIsNotChosen {
            get {
                return ResourceManager.GetString("CarIsNotChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  شماره پلاک یا شهر شماره گذاری یا سری وارد نشده است.
        /// </summary>
        internal static string CarIsNotExist {
            get {
                return ResourceManager.GetString("CarIsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای تاریخ وارد شده قبلاً پیام تعریف شده است و یا تاریخ اتمام قبل از تاریخ جاری است.
        /// </summary>
        internal static string DateRangeErrorEntered {
            get {
                return ResourceManager.GetString("DateRangeErrorEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از حذف مورد انتخاب شده اطمینان دارید؟.
        /// </summary>
        internal static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راننده ای انتخاب نشده است.
        /// </summary>
        internal static string DriverIsNotChosen {
            get {
                return ResourceManager.GetString("DriverIsNotChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخلف قبلی این مورد رفع نشده است.
        /// </summary>
        internal static string DuplicateInfraction {
            get {
                return ResourceManager.GetString("DuplicateInfraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از  انجام تغییرات اطمینان دارید؟.
        /// </summary>
        internal static string EditMessage {
            get {
                return ResourceManager.GetString("EditMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع نباید قبل از تاریخ پایان باشد.
        /// </summary>
        internal static string EndDateMoreThanStartDate {
            get {
                return ResourceManager.GetString("EndDateMoreThanStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل {0} یافت نشد.
        /// </summary>
        internal static string FileNotExists {
            get {
                return ResourceManager.GetString("FileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تردد ورود ثبت نشده است.
        /// </summary>
        internal static string NoInTraffic {
            get {
                return ResourceManager.GetString("NoInTraffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} مورد نظر یافت نشد.
        /// </summary>
        internal static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرویس ارسال اس ام اس قطع می باشد.
        /// </summary>
        internal static string SMSControllerOfflineAlarm {
            get {
                return ResourceManager.GetString("SMSControllerOfflineAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در این تاریخ  برای این محور بارگیر  یا این نوع تردد  یا این مراجعه به مبلغی تعریف نشده است.
        /// </summary>
        internal static string StopFeeNotExist {
            get {
                return ResourceManager.GetString("StopFeeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام برای تاریخ امروز قابل تغییر نمی باشد.
        /// </summary>
        internal static string TodayDate {
            get {
                return ResourceManager.GetString("TodayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترددی انتخاب نشده است.
        /// </summary>
        internal static string TrafficNotSelected {
            get {
                return ResourceManager.GetString("TrafficNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان این نوبت به پایان رسیده است آیا نوبت جدید داده شود؟.
        /// </summary>
        internal static string TurnTimeOver {
            get {
                return ResourceManager.GetString("TurnTimeOver", resourceCulture);
            }
        }
    }
}
